package com.order.orderservice.Dto;

public enum OrderStatus {
    ORDER_RECEIVED,
    ITEM_IN_STOCK,
    ORDER_FULFILLED,
    ORDER_CREATED,
    ORDER_COMPLETED,
    ORDER_SHIPPED,
    ORDER_CANCELLED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    SHIPMENT_CREATED,
    SHIPMENT_FAILED,
    SHIPMENT_COMPLETED,
    SHIPMENT_CANCELLED,
    ITEM_OUT_OF_STOCK,
    ORDER_CANCEL_REQUEST,
    PAYMENT_TIMED_OUT,
    SHIPMENT_TIMED_OUT
}
